-- ProofRecall Day 4: duplicate-quote guard for imports
-- Source of truth for the schema. Executed in the Supabase SQL Editor on 2026-09-18.
--
-- Why a generated hash column instead of a plain unique index on the quote:
--   1. A btree over raw `quote` would store the whole 2000-character text per
--      key; md5 keeps the index at 32 characters.
--   2. PostgREST can only target a conflict on *columns*, not expressions, so
--      the app needs a real column to say ON CONFLICT (user_id, quote_hash).
--      That is what lets the import routes use `upsert(..., { onConflict,
--      ignoreDuplicates })` and report per-row duplicates instead of failing
--      the whole batch on the first repeat.
--   3. The quote text itself stays untouched. "Re-import the same file" must
--      not rewrite what a customer actually said, so duplicates are skipped,
--      never merged.
--
-- Whitespace and case are normalised inside the hash, so the same quote typed
-- with double spaces, a trailing newline or different capitalisation counts as
-- one quote. Punctuation is NOT normalised: "Great!" and "Great" are different
-- quotes on purpose.
--
-- Scope: user_id is part of the key, so two customers may own identical quotes.
-- Because `tags` has no UPDATE policy, the guard must stay DO NOTHING (an
-- upsert merge would need UPDATE privileges that are deliberately not granted).
--
-- RLS note: ON CONFLICT DO NOTHING can only see conflicts among rows the
-- caller is allowed to read, which is exactly the owner's own rows — so a
-- duplicate held by another tenant can never be probed through this index.
--
-- NOTE: keep every statement free of `--` comments and on ONE line when pasting
-- into the dashboard SQL Editor — Monaco auto-indents multi-line input and
-- appends at the cursor instead of replacing it. Use exactly one fill per empty
-- tab, then run.
--
-- NOTE: the dashboard runs a whole batch inside ONE transaction. A verification
-- `raise exception '...'` at the end of a DO block therefore rolls the entire
-- batch back — the editor still prints your message, so the change looks applied
-- while the database is unchanged. Use `raise notice` for verification output
-- and confirm applied changes out of band (e.g. through PostgREST).

-- 1. The normalised fingerprint of the quote (stored, so it is indexable)
alter table public.testimonials
  add column if not exists quote_hash text generated always as (
    md5(lower(btrim(regexp_replace(coalesce(quote, ''), '\s+', ' ', 'g'))))
  ) stored;

comment on column public.testimonials.quote_hash is
  'md5 of the quote, whitespace-collapsed and lowercased. Never written by the app: generated by Postgres.';

-- 2. One copy of a quote per owner
create unique index if not exists testimonials_user_quote_hash_key
  on public.testimonials (user_id, quote_hash);

-- 3. No new privileges are needed: the guard rides the existing INSERT and
--    SELECT policies. Re-check the grants anyway (this project was created with
--    "Automatically expose new tables" DISABLED).
grant select on public.testimonials to anon, authenticated;
grant insert, update, delete on public.testimonials to authenticated;
